name: singleton_bloc
description: "A Wrapper for the traditional bloc pattern with single state."
version: 0.0.1
homepage: https://github.com/Mohammedirfan25/singleton_bloc.git

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter: null
